### ISSUE TITLE
problem with address text

### ISSUE THREAD

**Issue by geraluca** [EvotecIT/OfficeIMO#109] opened 2023-02-15 12:40 UTC
I ask for a courtesy, I really struggle to find a way to write the address of a letter with the text all to the right and the space between the lines reduced to the minimum possible, is there a solution? Thanks in advance for the possible reply

**Comment by PrzemyslawKlys** [comment] 2023-02-16 20:42
Duplicate of #107

**Closed by PrzemyslawKlys** 2023-02-16 20:42 UTC
