### ISSUE TITLE
Unable to format external hyperlinks

### ISSUE THREAD

**Issue by dstringvc** [EvotecIT/OfficeIMO#90] opened 2022-12-22 22:45 UTC
I'm trying to format external hyperlinks with custom font color and size, no underline, but cannot get anything other than the default font from the document.

I have tried setting the font attributes inline:
document.AddHyperLink("Go to Evotec Blogs", new Uri("https://evotec.xyz")).SetColorHex("1C8FD6").SetFontSize(14).SetBold();

I have tried setting the font attributes after the fact:
var paragraphWithHyperLink = document.AddHyperLink("Go to Evotec Blogs", new Uri("https://evotec.xyz"));
paragraphWithHyperLink.SetColorHex("1C8FD6").SetFontSize(14).SetBold();

I have tried creating the hyperlink off a new paragraph:
WordParagraph paragraph = document.AddParagraph();
paragraph.AddHyperLink("Go to Evotec Blogs", new Uri("https://evotec.xyz")).SetColorHex("1C8FD6").SetFontSize(14).SetBold();

None of these attempts have worked. Am I missing something? Thank you!

**Comment by PrzemyslawKlys** [comment] 2022-12-23 07:27
Neither can I, will see what's wrong with it.

**Comment by dstringvc** [comment] 2022-12-28 18:23
Any updates on the hyperlink issue? Is there anything I can do to help with the troubleshooting? Thank you!

**Comment by PrzemyslawKlys** [comment] 2022-12-28 21:47
I did play with it. I wanted HyperLink to inherit properties from Paragraph, so that it would have all the options from Paragraph (settable on the hyperlink itself). Unfortunetly my knowledge on inheritance and how to make some things is very limited, so I was struggling to fix it. I may as well copy code from Paragraphs (all properties/methods that touch RUnProperties on Paragraph) and let it be a "copy", that later on can be improved by someone who's better coder. 

Generally the problem is that Hyperlinks can contain runs and runs contains runproperties which  is what makes the hyperlink styling work. We don't have that now. What we have now happens on the run that's outside of hyperlink, but within paragraph. 

![image](https://user-images.githubusercontent.com/15063294/209875379-c7936945-d5ab-4e30-933c-28b7c3654955.png)

As with OpenXML usual approach it's possible that one Link, or a more the Text it binds to it's possible is split over multiple runs (think of a link that has multiple colors - not your standard, but it could happen). 

So there's no need to troubleshoot anything - more like help is needed to fix it properly, because as far as I see it - I can only fix it with a workaround, which may work, but should be improved later on.

**Comment by PrzemyslawKlys** [comment] 2023-01-14 10:31
It took a bit longer then expected. But it's now merged.

**Closed by PrzemyslawKlys** 2023-01-14 10:31 UTC
Labels: bug
